### ISSUE TITLE
besser keine emailadresse

### ISSUE THREAD

**Issue by martin-raden** [fabio-gut/IntaRNA#1]
https://github.com/fabio-gut/IntaRNA/blob/20f99f7ba62a1baa33009b1e3b68d45180161337/python/setup.py#L11

Moin @fabio-gut 
um spam zu umgehen, solltest du deine emailadresse besser nicht in den source code packen. zumal die ja eh mittelfristig sterben wird. wenn, dann würde ich eher so statische infos wie github accounts etc. angeben.

Aber ist nur ein Gedanke und mein persönliches Gusto, Entscheidung liegt natürlich bei dir! ;)

Grüsse,
Martin

**Comment by fabio-gut** [comment]
Hallo Martin,

hast absolut recht. Habe es überall durch meinen github link ersetzt!

Grüße,
Fabio
